### ISSUE TITLE
Model of the raspberry pi screen

### ISSUE THREAD

**Issue by vallettea** [MCMElectronics/Raspberry-Pi-Tablet#1]
Hello,

thanks for sharing. Do you know where I can find the model of the screen itself ?
Best

**Comment by vallettea** [comment]
Oh here it is:
http://www.thingiverse.com/thing:1044469

**Comment by makermichael** [comment]
Or here - http://www.mcmelectronics.com/product/83-16872

**Comment by vallettea** [comment]
couldn't find the link for the 3d model on your link ?

**Comment by makermichael** [comment]
Try this one - http://www.thingiverse.com/thing:1040389
