### ISSUE TITLE
What sort of licensing are you offering? 

### ISSUE THREAD

**Issue by navanjr** [MCMElectronics/Raspberry-Pi-Tablet#2]
Hi, Thanks for the clean model...  what sort of license are you offering to us?

**Comment by makermichael** [comment]
Hello - The model is free for personal use. For commercial use, let me know what you're thinking and we can discuss options.

**Comment by jasonnolan** [comment]
HI Michael; I'm using it for a non-personal, non-commercial use, building prototypes of augmented and alternative communication devices for disabled children in Bolivia. I assume that that's good as well?  As well, I've made some mods that are useful to me, I guess I should upload and link them back here?

**Comment by navanjr** [comment]
Commercial kiosk time & attendance.  
We would need to a non-exclusive onetime purchase price.
Thanks for your consideration
